config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :posts
  root 'feed#index'
  post '/' => 'posts#create'
  get 'users/:username' => 'users#display_user', as: 'profile'
  get 'users/:username/bookmarks' => 'users#bookmarks#', as: 'bookmarks'

  get '/search' => 'search#search'

  get 'users/follow/:id' => 'users#follow' 
  get 'users/unfollow/:id' => 'users#unfollow'

  get '/feed/:id_last_post' => 'feed#get_feed'
  get '/user/:username/:id_last_post' => 'users#get_feed_user'
  get '/user/bookmarks/:username/:id_last_post' => 'users#get_bookmarks_user'
  
  get 'posts/add_bookmark/:id' => 'posts#add_bookmark' 
  get 'posts/remove_bookmark/:id' => 'posts#remove_bookmark'

  get 'posts/add_repost/:id' => 'posts#add_repost' 
  get 'posts/remove_repost/:id' => 'posts#remove_repost'

  get 'suggest/suggestusers' => 'feed#get_suggest_users'
  get 'suggest/suggestposts' => 'feed#get_suggest_posts'

  get '/search/by_hash/:q/:id' => 'search#get_posts_with_hashtags_for_search'
  get '/search/by_posts/:q/:id' => 'search#get_posts_for_search'
  get '/search/by_users/:q/:id' => 'search#get_users_for_search'

  

end

app/controllers/feed_controller.rb
class FeedController < ApplicationController

  def index
   if current_user 
    @users = current_user.get_suggest_users
    @posts_suggest = current_user.get_suggest_posts

    @posts = current_user.feed
    puts @posts
    end 
  end

  def get_feed
    @posts = current_user.feed(params[:id_last_post])
    (!@posts.empty?) ? (render partial: "posts/posts_list") : (render text: "0")
  end


  def get_suggest_users
  	@users = current_user.get_suggest_users  	
  	(!@users.empty?) ? (render partial: "suggestusers") : (render text: "no suggest")
  end

  def get_suggest_posts
    @posts_suggest = current_user.get_suggest_posts
    (!@posts_suggest.empty?) ? (render partial: "suggestposts") : (render text: "no suggest")
    
  end





end

app/views/feed/_suggestposts.html.erb
<ul>
<% @posts_suggest.each do |post| %>
    <li><%= link_to post.url, post %></li>
<% end %>
</ul>

app/views/feed/_suggestusers.html.erb
<ul>
<% @users.each do |user| %>
    <li class="follow-container clearfix">
    	<%= link_to image_tag(user.picture.url(:thumb), :class => "avatar-30 profile-follow-pic"), profile_path(user.username) %> <%= link_to user.username, profile_path(user.username), :class => "profile-follow-name" %>
    	<a href="#" class="js-follow sugg-follow" data-id="<%= user.id %>" data-state=<% (@follows_current_user.include?(user)) ? ( %>"0"<% ) :( %>"1"<% ) %>><% (@follows_current_user.include?(user)) ? ( %>-<% ) :( %>+<% ) %></a>
    </li>
<% end %>
</ul>

app/views/feed/index.html.erb
<% if @current_user %>
  <div class="col-7-12"><!-- CENTRAL COLUMN -->
     <div class="content" id="new-post"><!-- NEW POST -->
        <div>
        <%= form_for :post, url: "/", :html => {name: 'post-article', id: 'post-article'} do |f| %>
          <%= f.text_field :url, :id=>"post_url", :placeholder=>"Insérez une URL pour ajouter un contenu", :class => "form-field", :value=>"http://" %>
          <div id="form-extended">
            <%= f.text_field :content, :id=>"desc", :placeholder=>"Message accompagnant le contenu", :class => "form-field" %>
            <div class="post-hashtag"><%= f.text_field :hashtag, :class => "post-hashtag form-field" %></div>
            <%= f.submit "Envoi", :class => "form-field" %>
          </div>
        <% end %>
       </div>
     </div><!-- END NEW POST -->
     <div class="content"><!-- FEED -->
        <section id="zone_post">
          <% if @current_user %>    
            <%= render partial: "posts/posts_list" %>
          <% end %>
        </section>
        <div class="post-loader transparent">
          <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
          </div>
        </div>
       </div><!-- END FEED -->
    </div><!-- END CENTRAL COLUMN -->

  <div class="col-3-12"><!--  RIGHT COLUMN -->
    <div class="content">
      <h2>Suggestions</h2>
      <h3 class="full title-rel">
        <img src="img/icons/users_suggestions.svg" class="icon-titles" alt="">
        Utilisateurs
        <a href="#" id="suggest_follows_button" class="title-button">
          <img src="img/icons/sync.svg" class="icon-sync" alt="">
        </a>
      </h3>
      
      <div id="suggest_follow" class="follow-div">
        <%= render partial: "suggestusers" %>
      </div>
      <h3 class="full title-rel">
        <img src="img/articles.png" class="icon-titles" alt="">
        Articles
        <a href="#" id="suggest_articles_button" class="title-button">
          <img src="img/icons/sync.svg" class="icon-sync" alt="">
        </a>
      </h3>
      <div class="suggestion-article-wrapper">
        <div id="suggest_articles" class="suggest-article">
          <%= render partial: "suggestposts" %>
        </div>
      </div>
    </div> <!-- END CONTENT SUGGESTIONS -->
  </div><!-- END RIGHT COLUMN -->

  <script>
    // this is important for IEs
    var polyfilter_scriptpath = 'javascripts/';
  </script>

<% end %>