config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :posts
  root 'feed#index'
  post '/' => 'posts#create'
  get 'users/:username' => 'users#display_user', as: 'profile'
  get 'users/:username/bookmarks' => 'users#bookmarks#', as: 'bookmarks'

  get '/search' => 'search#search'

  get 'users/follow/:id' => 'users#follow' 
  get 'users/unfollow/:id' => 'users#unfollow'

  get '/feed/:id_last_post' => 'feed#get_feed'
  get '/user/:username/:id_last_post' => 'users#get_feed_user'
  get '/user/bookmarks/:username/:id_last_post' => 'users#get_bookmarks_user'
  
  get 'posts/add_bookmark/:id' => 'posts#add_bookmark' 
  get 'posts/remove_bookmark/:id' => 'posts#remove_bookmark'

  get 'posts/add_repost/:id' => 'posts#add_repost' 
  get 'posts/remove_repost/:id' => 'posts#remove_repost'

  get 'suggest/suggestusers' => 'feed#get_suggest_users'
  get 'suggest/suggestposts' => 'feed#get_suggest_posts'

  get '/search/by_hash/:q/:id' => 'search#get_posts_with_hashtags_for_search'
  get '/search/by_posts/:q/:id' => 'search#get_posts_for_search'
  get '/search/by_users/:q/:id' => 'search#get_users_for_search'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nabu</title>
  <link rel="icon" type="image/x-icon" href="/img/favicon.ico" />
  <%= stylesheet_link_tag 'style' %>
  <%= stylesheet_link_tag 'simplegrid' %>
  <%= stylesheet_link_tag 'component' %>
  <%= javascript_include_tag 'custom.modernizr' %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag :application %>
</head>
<body class="<%= @current_user == @target_user ? "current_user" : ""%>">
<div id="wrapper" style="background: url('<%= @target_user.background %>') repeat fixed">  
  <% if notice %>
    <div class="alert alert-success"><%= notice %></div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger"><%= alert %></div>
  <% end %>

  <div id="left"><!-- LEFT PART -->
    <div id="sidebar"><!-- SIDEBAR -->
      <div id="sidebar-cover">
          <%= image_tag(@target_user.picture.url(:sidebar), :class => "full res blur") %>
      </div>
      <div id="sidebar-content">
         <div class="content">
          <%= image_tag(@target_user.picture.url(:thumb), :class => "avatar-main") %><br>
          <a href="/users/<%= @target_user.username %>" class="user-name"><%= @target_user.username %></a>
          <% if @target_user.description && @target_user.description.size > 1 %>
             <span class="user-description">" <%= @target_user.description %> "</span>
          <% end %>
          <div class="posts-number">
            <a href="/users/<%= @target_user.username %>">
              <span class="follow-number"><%= @nb_posts %></span> posts
            </a>
          </div>
          <div class="bookmarks-number">
            <a href="/users/<%= @target_user.username %>/bookmarks">
              <span class="follow-number"><%= @nb_bookmarks %></span> bookmarks
            </a>
          </div>
          <div id="stats-followers" class="follow-numbers-container"><span class="follow-number" id="nb_followers"><%= @followers.size %></span> followers</div>
          <div id="stats-following" class="follow-numbers-container"><span class="follow-number" id="nb_following"><%= @followings.size %></span> following</div>
          <% if @target_user != @current_user %>
            <div class="follow-container">
              <a href="#" class="js-follow profile-unfollow-button" data-id="<%= @target_user.id %>" data-state="<% (@follows_current_user.include?(@target_user)) ? ( %>0<% ) :( %>1<% ) %>">
                <% (@follows_current_user.include?(@target_user)) ? ( %>Ne plus suivre<% ) :( %>Suivre<% ) %>
              </a>
            </div>
          <% end %>
         </div>
          <%= render partial: "users/follow" %>
      </div>
    </div><!-- END SIDEBAR -->
  </div><!-- END LEFT PART -->

  <div id="right"><!-- RIGHT PART -->
    <div class="grid grid-pad" id="top-content"><!-- GRID LOGO/SEARCH/MENU -->
      <div class="col-7-12" id="logo"><!-- LOGO AND SEARCHBAR -->
          <h1><a href="/"><img src="<%= root_path %>img/logo_nabu.svg" alt="Nabu"></a></h1>
          <div id="search">
            <form action="/search" method="get">
              <input type="text" name="q" autocomplete="off" placeholder="Rechercher">
              <div><img src="<%= root_path %>img/icons/loupe.svg"  class="icon-search" alt="Rechercher"></div>
            </form>
          </div>
      </div><!-- END LOGO AND SEARCHBAR -->
      <div class="col-3-12" id="menu"><!-- MENU -->
        <p>
          <a href="/users/<%= @current_user.username %>">
            <img src="<%= root_path %>img/icons/user.svg" class="icon-menu" alt="Profil">
          </a>
          <a href="/users/edit">
           <img src="<%= root_path %>img/icons/settings.svg" class="icon-menu" alt="Paramètres">
          </a>
          <a href="/users/sign_out">
            <img src="<%= root_path %>img/icons/power.svg" class="icon-menu" alt="Déconnexion">
          </a>
        </p>
      </div><!-- END MENU -->
    </div><!-- END GRID LOGO/SEARCH/MENU -->

    <div class="grid grid-pad"><!-- GRID CONTENT -->
      
       <%= yield %>

    </div><!-- END GRID CONTENT -->
      </div><!-- END RIGHT PART -->
    </div>

    <!--popup settings : html popup + scripts-->


    <div class="md-overlay"></div><!-- the overlay element -->

    <%= javascript_include_tag 'cssParser' %>
    <%= javascript_include_tag 'classie' %>
    <%= javascript_include_tag 'modalEffects' %>
    <%= javascript_include_tag 'modernizr.custom' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-1.10.2.min.js' %>
    <%= javascript_include_tag 'snap.svg' %>
    <%= javascript_include_tag 'nabu' %>

</body>
</html>

app/views/layouts/landing.html.erb
<!doctype html>
<html lang="fr">
<head>
  <title>Nabu</title>
  <%= stylesheet_link_tag 'home' %>
  <%= stylesheet_link_tag 'simplegrid' %>
  <%= stylesheet_link_tag 'component' %>
  <%= csrf_meta_tags %>
</head>

<body>

  <header>
      <h1><img src="/img/logo_nabu.svg"/ class="logo-landing"></h1>
    <a class="md-trigger" data-modal="modal-login">Se connecter</a>
  </header>
  
  <div id="banner">
    <div id="bannertext">
      <h1>Voici Nabu</h1>
      <p>Découvrez, partagez, devenez source de curiosité.</p>
        <a class="md-trigger" data-modal="modal-signin">Essayer</a>
    </div>
  </div>

  
</section> <!-- Fin grid pad -->

  
  <article id="team">
    <section class="grid grid-pad">
    
    <h3>L'équipe</h3>
      
    <div class="col-2-12">&nbsp;</div>  
  
      <div class="col-2-12">
        <h4>A.-Sophie Valleray</h4>
        <div id="As"></div>
      </div>

      <div class="col-2-12">
        <h4>Erwan Martin</h4>
        <div id="Erwan"></div>
      </div>
      
      <div class="col-2-12">
        <h4>Lucie Reitz</h4>
        <div id="Lucie"></div>
      </div>

      <div class="col-2-12">
        <h4>Marion Livet</h4>
        <div id="Marion"></div> 
      </div>
      
      
    <div class="col-2-12">&nbsp;</div>
      
    </section>
  </article>
  
  
  <!-- POPUP -->  
    
    <div class="md-modal md-effect-10" id="modal-signin">
      <div class="md-content">
        <h3>Inscrivez-vous</h3>
        <div>

          <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>

            <%= devise_error_messages! %>

            <div class="field">
              <%= f.label :email %>
              <%= f.email_field :email, required: true, :class => "form-field--wlabel form-field" %>
            </div>

            <div class="field">
              <%= f.label :username %>
              <%= f.text_field :username, :class => "form-field--wlabel form-field" %>
            </div>

            <div class="field">
              <%= f.label :password %>
              <% if @validatable %>
              <em>(<%= @minimum_password_length %> caractères au minimum)</em>
              <% end %>
              <%= f.password_field :password, autocomplete: "off", required: true, :class => "form-field--wlabel form-field" %>
            </div>

            <div class="field">
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation, autocomplete: "off", required: true, :class => "form-field--wlabel form-field" %>
            </div>

            <div class="actions align-center">
              <%= f.submit "S'inscrire", :class => "form-field" %>
            </div>
          <% end %>
          <button class="md-close hidden">Close me!</button>
        </div>
      </div>
    </div>

    <div class="md-modal md-effect-10" id="modal-login">
      <div class="md-content">
        <h3>Identifiez-vous</h3>
        <div>

          <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>

            <% if flash %>
              <div class="alert-error">
              <% flash.each do |name, msg| %>
                <%= content_tag :p, msg if msg.is_a?(String) %>
              <% end %>
              </div>
            <% end %>

            <div class="field">
              <%= f.label :email %>
              <%= f.email_field :email, required: true, :class => "form-field--wlabel form-field" %>
            </div>

            <div class="field">
              <%= f.label :password %>
              <%= f.password_field :password, autocomplete: "off", required: true, :class => "form-field--wlabel form-field" %>
            </div>

            <% if devise_mapping.rememberable? -%>
              <div class="field">
                <%= f.check_box :remember_me %>
                <%= f.label :remember_me, :class => "auto" %>
              </div>
            <% end -%>

            <div class="actions align-center">
              <%= f.submit "Se connecter", :class => "form-field" %>
            </div>
          <% end %>
                    
          <button class="md-close hidden">Close me!</button>
        </div>
      </div>
    </div>
  

  
<div class="md-overlay"></div><!-- the overlay element -->

<script>
  // this is important for IEs
  var polyfilter_scriptpath = '/js/';
</script>

<%= javascript_include_tag 'cssParser' %>
<%= javascript_include_tag 'css-filters-polyfill' %>
<%= javascript_include_tag 'classie' %>
<%= javascript_include_tag 'modalEffects' %>
<%= javascript_include_tag 'modernizr.custom' %>
<%= javascript_include_tag 'https://code.jquery.com/jquery-1.10.2.min.js' %>
<%= javascript_include_tag 'main' %>
  
</body>

</html>